server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;
  add_header Permissions-Policy "camera=(self)" always;

  include /etc/nginx/mime.types;
  types {
    application/wasm wasm;
    model/gltf-binary glb;
    application/octet-stream task spz;
  }

  location = /health.txt {
    access_log off;
    add_header Cache-Control "no-store";
    try_files $uri =404;
  }

  location ~* \.(js|css)$ {
    expires 1y;
    add_header Cache-Control "public, immutable";
    try_files $uri =404;
  }

  location ~* \.(glb|spz|task|wasm)$ {
    expires -1;
    add_header Cache-Control "public, max-age=0, must-revalidate";
    try_files $uri =404;
  }

  location / {
    try_files $uri $uri/ /index.html;
    add_header Cache-Control "no-cache";
  }

  gzip on;
  gzip_types text/css application/javascript application/json application/wasm;
}
